### ISSUE TITLE
Any chance we can merge develop to master?

### ISSUE THREAD

**Issue by pshrosbree** [autofac/Autofac.ServiceFabric#11]
Some of @alexperovich's commits are very useful. It would be great if they were part of the NuGet.
What is the process for getting them there?

**Comment by alexmg** [comment]
I've just pushed 1.0.0-beta2 to NuGet.

**Comment by pshrosbree** [comment]
Great news! Thanks.

**Comment by alexmg** [comment]
No problem. Let me know how it goes.
