### ISSUE TITLE
Is there support for polymorphic actors or Generic Services 

### ISSUE THREAD

**Issue by vikramadhav** [autofac/Autofac.ServiceFabric#14]
Is there support for polymorphic actors or Generic Services,

**Comment by alexmg** [comment]
You can use the polymorphic actors as described in the official document.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-polymorphism

Unfortunately, generic interfaces are not yet supported in Service Fabric services.

https://github.com/Azure/service-fabric-services-and-actors-dotnet/issues/21
