### ISSUE TITLE
Create a 1.0 release

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac.ServiceFabric#15]
There have been a few good PRs and a number of pre-release packages so I think it's time to push out the official release.

**Comment by pshrosbree** [comment]
It would be really good if this could be netstandard2.0 compliant. Microsoft.ServiceFabric 6.1.211-preview is netstandard2.0 compliant, so they're very nearly there.

**Comment by pshrosbree** [comment]
I spoke to the Service Fabric team, and they are probably a few months away from a final release of a netstandard2.0 package, so I retract the suggestion above.

**Comment by alexmg** [comment]
Thanks for the information @pshrosbree. I will leave the 1.0.0 version on net452 to avoid breaking things just before the release. When the final netstandard2.0 package is available (or closer to the time) I'll go through the project and build migration process and release a 2.0.0 when everything is stable. Feel free to pop back and create another issue if you notice the netstandard2.0 release is available and things haven't moved along.

**Comment by alexmg** [comment]
The 1.0.0 release has now been pushed to NuGet.org.
