### ISSUE TITLE
The type 'System.Fabric.StatefulServiceContext' is not assignable to service 'System.Fabric.StatelessServiceContext'

### ISSUE THREAD

**Issue by artemkuzmyk** [autofac/Autofac.ServiceFabric#16]
https://github.com/autofac/Autofac.ServiceFabric/blob/590aba5d0b3df1702d3b063b708d2d0615cfb3a4/src/Autofac.Integration.ServiceFabric/ActorFactoryRegistration.cs#L49

Seems like misspelling here 
Must be:
` builder.RegisterInstance(context).As<StatefulServiceContext>().As<ServiceContext>();`

**Comment by artemkuzmyk** [comment]
It's a blocker for me to use actor with this libary :(

**Comment by alexmg** [comment]
Looks like a typo that slipped through in a PR. I'm about to do the 1.0.0 release and this fix will be included. Glad you caught it just in time! 👍

**Comment by alexmg** [comment]
@artemkuzmyk I've pushed the 1.0.0 release to NuGet that includes this fix. Please let me know if you find any other problems.

**Comment by artemkuzmyk** [comment]
Good job, thanks
