### ISSUE TITLE
There is a plan to sign the assembly?

### ISSUE THREAD

**Issue by MonDeveloper** [autofac/Autofac.ServiceFabric#19]
In order to use the library we had to remove the **digital signature** from our services, do you have plan to add the **digital signature** to the library?

**Comment by alexmg** [comment]
I didn't actually realise that it wasn't signed. We normally sign all our assemblies. This is certainly something I can do.

**Comment by alexmg** [comment]
@MonDeveloper I suspect I didn't read your original comment properly. We have already signed the assembly with a strong name key so I assume that you must be referring to an actual code signing certificate. If that is the case then we do not currently sign any of our assemblies with a digital certificate.

**Comment by MonDeveloper** [comment]
You're right, I'm really sorry, I open the issue in the wrong repo.
Again, sorry @alexmg
