### ISSUE TITLE
RegisterStatelessService doesn't work inside Modules

### ISSUE THREAD

**Issue by toddweb** [autofac/Autofac.ServiceFabric#2]
RegisterStatelessService() called within a Module.Load() results in the StatelessService instance not being spun up/created. There are no errors, just nothing happens. Interestingly, RegisterServiceFabricSupport() can be placed in the module and everything works as expected, as long as RegisterStatelessService() is outside of a Module.Load().

**Comment by alexmg** [comment]
Looks like the container build callbacks are not firing for modules. I'll have to take a look at this in the core Autofac library.

**Comment by alexmg** [comment]
I have created autofac/Autofac#849 to address the underlying issue. This will be released in Autofac 4.6.

**Comment by toddweb** [comment]
Thanks alexmg

**Comment by alexmg** [comment]
Just pushed a 1.0.0-beta1 package to NuGet. Let me know if you have any problems.
