### ISSUE TITLE
Autowired Properties

### ISSUE THREAD

**Issue by MonDeveloper** [autofac/Autofac.ServiceFabric#20]
In another project where we use Autofac we massively used the "WithAutoWiredProperties" concept, we also customize the properties resolutor in order to drive the choice of the properties to AutoWire using a custom Attribute.
Everything worked fine and we were happy.
As far as I've understood, it is not possible to do the same with this Extension, I mean, it is not possible to add some "With" to the ServiceFabric services/actors registration.
What can be the solution to add such a behavior?

**Comment by alexmg** [comment]
@MonDeveloper It looks like I could return the `IRegistrationBuilder` from the `RegisterActor`, `RegisterStatelessService`, and `RegisterStatefulService` methods. This would allow for additional configuration to be performed, but it would also make it possible for someone to break the registrations, such as if the lifetime was changed from `InstancePerLifetimeScope`.

I personally prefer constructor injection to property injection as it makes the required dependencies clear and incurs a lower runtime performance cost. Is there another example of registration configuration that you feel would be beneficial to be able to configure on the service registrations?

**Comment by alexmg** [comment]
The RegisterActor, RegisterStatefulService and RegisterStatelessService methods now return an IRegistrationBuilder allowing for further configuration of the registration. This will be included in the next release.

**Comment by alexmg** [comment]
I have pushed a 1.1.0 package to NuGet.
