### ISSUE TITLE
Autofac.ServiceFabric Dependencies Incompatible With Microsoft.ServiceFabric.AspNetCore.Kestrel

### ISSUE THREAD

**Issue by mkrain** [autofac/Autofac.ServiceFabric#24]
Any chance to update the reference packages?  I'm getting this error when trying to use ASP.NET Core Kestrel:

Error CS1705 Assembly 'Microsoft.ServiceFabric.AspNetCore.Kestrel' with identity 'Microsoft.ServiceFabric.AspNetCore.Kestrel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Fabric' with identity 'System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

This is because Autofac.ServiceFabric depends on Microsoft.ServiceFabric.Actors which in turn depends on Microsoft.ServiceFabric, which again depends on System.Fabric (the incompatible version).

Also would it be better to break out the Actors vs Stateless vs Stateful integrations into their own packages?

**Comment by tillig** [comment]
If adding a direct reference to the 6.0 version of the `System.Fabric` library doesn't fix it, then this is likely somewhat related to the #18 issue where various libraries are pinning exact match versions rather than ranges. Rather than track this twice, we can fight version issues in #18.
