### ISSUE TITLE
Upgrade to Service Fabric 6.1

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac.ServiceFabric#27]

**Comment by alexmg** [comment]
The projects have been upgraded to .NET Core in beb6172427916f442ba57f69babae28f3e53beb1 and now targets `netstandard2.0` and `net452`. Build and unit tests are passing on both target frameworks.

Please grab the latest CI package from our MyGet feed and let me know how it goes for you. Hopefully things go well and this can move quickly to release.

https://www.myget.org/F/autofac/api/v3/index.json

I have bumped the package version to `2.0.0` for this release. The first `2.0.0` dev build on the MyGet feed is `2.0.0-develop-00034`.

**Comment by snaits** [comment]
Thanks  @alexmg , great work! 

I've upgraded an app with 14 services, all seem to be alive and well locally. Actors and stateless services, some .NET Core and some not. I hope as you do, that this can go into release quickly 🤞

**Comment by alexmg** [comment]
Thanks for the feedback @snaits! That's really helpful.

I've pushed another update to MyGet: `Autofac.ServiceFabric.2.0.0-develop-00035`

This updates `Autofac.Extras.DynamicProxy` dependency to `4.4.0` due to the issue below.

https://github.com/autofac/Autofac.Extras.DynamicProxy/issues/25

I also added an explicit `x64` platform target for both target frameworks (`netstandard2.0` and `net452`).

@snaits It would be great if you could put this update through its paces too, and if it works for you I'll push it as a release to NuGet.org.

**Comment by snaits** [comment]
Sure, I'll try to have a look at this today. Should find the time, but tomorrow at the latest.

**Comment by snaits** [comment]
I've updated to Autofac.ServiceFabric.2.0.0-develop-00035 and deployed it five hours ago. I haven't seen any issues so far 👍

**Comment by pshrosbree** [comment]
All good with Autofac.ServiceFabric.2.0.0-develop-00035

**Comment by mccow002** [comment]
I've been using Autofac.ServiceFabric.2.0.0-develop-00035 for stateless services, and everything works great.

**Comment by alexmg** [comment]
Thank you @snaits, @pshrosbree and @mccow002!

I have pushed a 2.0.0 release package to NuGet. 😃
