### ISSUE TITLE
Publish nuget package with support of Service Fabric > 3.0.0

### ISSUE THREAD

**Issue by fcastellscha** [autofac/Autofac.ServiceFabric#28]
We cannot upgrade to the latest Service Fabric packages, because we get the following error:

Unable to resolve dependencies. 'Microsoft.ServiceFabric.Actors 3.0.456' is not compatible with 'Autofac.ServiceFabric 1.1.0 constraint: Microsoft.ServiceFabric.Actors (>= 2.4.164 && < 3.0.0)'.

**Comment by snaits** [comment]
This is under way, see issue #27  - I've tried the myget build, it works very well 👍

**Comment by fcastellscha** [comment]
Close as duplicate of #27
