### ISSUE TITLE
Split nuget package into individual packages for Stateless, Stateful and Actors

### ISSUE THREAD

**Issue by fcastellscha** [autofac/Autofac.ServiceFabric#29]
Currently, this package adds dependencies to the 3 types of SF services even if only one dependency is required.

**Comment by tillig** [comment]
PR #60 is open for this at the moment, but I don't know if... honestly, if this really matters. It's not uncommon for framework/integration libraries to potentially add some dependencies you're not going to use. It makes it easier for the owners of the library (us) to maintain it if it's not two different packages, and if everything is versioned/updated at the same time in the integration library, there's not any actual harm. It's not entirely unlike things like ASP.NET MVC adding several references to things you may not want; it's still pay-for-play, and if you don't use it, you don't use it.

If there is some actual technological detriment to having these here ("X doesn't work if Y is present," "X performs worse if Y is also referenced-but-unused") I'd be happy to reopen this provided those explanations.
