### ISSUE TITLE
Ability to set ActorServiceSettings

### ISSUE THREAD

**Issue by Mardoxx** [autofac/Autofac.ServiceFabric#3]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-lifecycle#actor-deactivation

**Comment by alexmg** [comment]
Good catch @Mardoxx. I'll take a look at this.

**Comment by Mardoxx** [comment]
That was quick!

**Comment by alexmg** [comment]
I ended up adding pass through for all the optional ActorService constructor parameters while I was in there.

**Comment by alexmg** [comment]
Just pushed a 1.0.0-beta1 package to NuGet. Let me know if you have any problems.
