### ISSUE TITLE
InstancePerMatchingLifetimeScope

### ISSUE THREAD

**Issue by wasabii** [autofac/Autofac.ServiceFabric#30]
This project should register the lifetime scope with a tag, so that additional things can be configured to register within the same scope but not lower. Since it promotes hosting multiple service instances in a single root container, this seems quite wise.

The tag should also be configurable.

**Comment by wasabii** [comment]
#31

**Comment by alexmg** [comment]
This change is in `Autofac.ServiceFabric 2.1.0-develop-00053` on our MyGet feed (`https://www.myget.org/F/autofac/api/v3/index.json`). It would be awesome if you could give it a test.
