### ISSUE TITLE
How to inject custom ActorService

### ISSUE THREAD

**Issue by jefersonmanjos** [autofac/Autofac.ServiceFabric#36]
Hi! I'm trying to use autofac to register custom actor services like I do with this code:

`ActorRuntime.RegisterActorAsync<StartupAgent>((context, actorType) => new StartupService(new ConfigurationsSettings(context), new ActorProxyService(), context, actorType)).GetAwaiter().GetResult();`

There is a way to do somethings like this:

`builder.RegisterActor<StartupAgent>((context, actorType) => new StartupService(new ConfigurationsSettings(context), new ActorProxyService(), context, actorType));` ?

Thanks

**Comment by MattHartz** [comment]
@alexmg  @pvivera I see the PR, not sure how I can translate @jefersonmanjos 's suggestion into implementation.

Any help would be amazing! Thanks

**Comment by MattHartz** [comment]
Actually I get it nvm!
