### ISSUE TITLE
Understanding scope in a stateless service.

### ISSUE THREAD

**Issue by Mardoxx** [autofac/Autofac.ServiceFabric#4]
I thought I'd ask here, as clearly you are interested in Service Fabric and an expert on all DI/IoC matters! 😄 

How are service lifetimes managed within a service? What is the "scope" of an `IService`?

Let's say I have the following setup:

My Store/DAL:

```cs
public interface IUserStore
{
    Task<string> GetNameAsync(int Id);
}
```

```cs
public class UserStore : IUserStore
{
    private readonly IUserDbContext _context;

    public UserStore(IUserDbContext context) {
        _context = context;
    }

    public async Task<string> GetNameAsync(int id)
    {
        return _context.Users.FirstOrDefault(x => x.Id == id)?.Name;
    };
}
```

My Service interface:

```cs
public interface IUserService : IService
{
    Task<string> GetNameAsync(int Id);
}
```

```cs
public class UserService : IUserService
{
    private readonly IUserStore _userStore;

    public UserService(IUserStore userStore)
    {
        _userStore = userStore;    
    }

    public async Task<string> GetNameAsync(int id)
    {
        return await _userStore.GetName(id);
    }
}
```

I resolve my service using

```cs
ServiceProxy.Create<IUserService>(new Uri("fabric:/Users/UserService"))
```

I have been, perhaps naively, using `Microsoft.Extensions.DependencyInjection`. My service registration looked like this:

```cs
ActorRuntime.RegisterServiceAsync("UserService",
    context =>
    {
        var services = new ServiceCollection();
        services.AddDbContext<UserDbContext>(builder => builder.UseSqlServer("connectionString"));
        services.AddScoped<IUserDbContext, UserDbContext>();

        services.AddTransient<IUserStore, UserStore>();

        var serviceProvider = services .BuildServiceProvider();
        return serviceProvider.GetRequiredService<UserService>();
    }).GetAwaiter().GetResult();
```

This does not appear to work correctly. When I resolve my `IUserService` and call a method on it, it resolves to the already existing service which has already been constructed with its dependencies injected. With these stateless services there is no notion, or at least it appears that way, of a request/lifetime scope as you would have in say, an ASP.NET web application. The lifetime scope is basically the life of the service - which is indeterminate (read: infinite). This means I effectively have a singleton instance of the `DbContext` (and its corresponding change tracker) for the lifetime of my application. Which is pretty unacceptable really? Surely you'd want to resolve one per request to the service.

What I'd imagine you'd want is for it to work in a familiar manner -- i.e. similar to how service resolution works with ASP.NET web projects (see diagrams [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#service-lifetimes-and-registration-options)).

I suppose what I am wondering is, how do (or how do you expect) constructor injection to work (with appropriate lifetimes) within a service?

One solution is to use Actors, since each call to create a `*Actor` from the `*ActorService` creates a new instance of `*Actor`. However I am not entirely sure if this is an entirely sensible solution.

-----

This of course isn't _directly_ related to `Autofac.ServiceFabric` but with DI and Service Fabric Services in general, which you may be able to address! I did refactor the above to use this library, but the same issue remains, my dependencies are't (can't?) be recreated per request to my `IService`. The only (I don't mean that in a diminutive way at all!!) thing I believe this library does additionally is that when tearing down a service it GC's stuff correctly.

**Comment by Mardoxx** [comment]
For information: https://github.com/Azure/service-fabric-issues/issues/269#issuecomment-301893718

**Comment by alexmg** [comment]
Yes, in the case of a stateless service its lifetime is essentially a singleton. The primary reason for supporting these in the integration is to provide a consistent pattern for working with DI in all types of SF services. You can also use the more natural `IDisposable` pattern and have the container dispose the appropriate services for you when the service is deactivated.

If you want to have dependencies that should exist only for the duration of a method invocation you can achieve this using an auto-generated factory (`Func<T>`). In the case that you need to control disposal of this dependency you can also combine that with an owned dependency (`Func<Owned<T>>`) and dispose the instance of `T` immediately after you have finished with it in the method. You can find out more about these _relationship types_ on our documentation site.

http://docs.autofac.org/en/latest/resolve/relationships.html

In the example you provided a basic auto-generated factory approach would look something like this:

```
public class UserService : IUserService
{
	private readonly Func<IUserStore> _userStoreFactory;

	public UserService(Func<IUserStore> userStoreFactory)
	{
		_userStoreFactory = userStoreFactory;
	}

	public async Task<string> GetNameAsync(int id)
	{
		return await _userStoreFactory().GetNameAsync(id);
	}
}
```

If the `IUserStore` implemented `IDisposable` and needed to release resources eagerly it would look more like this:

```
public class UserService : IUserService
{
	private readonly Func<Owned<IUserStore>> _userStoreFactory;

	public UserService(Func<Owned<IUserStore>> userStoreFactory)
	{
		_userStoreFactory = userStoreFactory;
	}

	public async Task<string> GetNameAsync(int id)
	{
		using (var userStore = _userStoreFactory().Value)
		{
			return await userStore.GetNameAsync(id);
		}		
	}
}
```

I would also configure and build your container outside of the factory delegate so you don’t accidentally apply the same pattern when working with other types of services (such as reliable actors) and end up creating multiple instances of the container. When you use the integration all your services (including the SF services) are registered up front before building the container so this wouldn't be an issue.

Hope that helps. 😃

**Comment by Mardoxx** [comment]
Absolutely perfect, thanks so much! This appears to be exactly what I was looking for. I had no idea AutoFac was this powerful. What a great piece of kit! I shall have a play with this in the coming days 😄

**Comment by Mardoxx** [comment]
I've now implemented this and it works brilliantly.

I opted for

```
public class UserService : IUserService
{
	private readonly Func<Owned<IUserStore>> _userStoreFactory;

	public UserService(Func<Owned<IUserStore>> userStoreFactory)
	{
		_userStoreFactory = userStoreFactory;
	}

	public async Task<string> GetNameAsync(int id)
	{
		using (var userStore = _userStoreFactory())
		{
			return await userStore.Value.GetNameAsync(id);
		}		
	}
}
```

This way, correct me if I'm wrong, a new scope is created per method call. So any services which are registered as _per scope_ (or transient) will be constructed and then destroyed at the end of this call - In this case the `IUserDbContext`. Seems to work as I wanted anyway, unless this is not a sensible thing to do?

**Comment by alexmg** [comment]
Glad it is working well for you. Yes, the store and its dependencies will be created in their own lifetime scope that will be disposed at the end of the using, essentially making it instance per method call. 👍

**Comment by tillig** [comment]
[I added some quick docs around the Service Fabric integration](http://autofac.readthedocs.io/en/latest/integration/servicefabric.html) which includes this faux per-request info so hopefully it'll help folks in the future.
